name: "CI"

on:
  push:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: build-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    name: ${{ matrix.java }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: 'gradle'

      - name: Run build and tests
        run: ./gradlew clean build test --stacktrace --no-daemon
