name: "CI"

on:
  push:
  pull_request:

concurrency:
  cancel-in-progress: true
  group: build-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
    name: ${{ matrix.java }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          check-latest: true
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: always
          cache-cleanup: on-success
          cache-read-only: ${{ github.ref != 'refs/heads/v3' }}

      - name: Run build and tests
        run: ./gradlew clean build test --stacktrace --no-daemon

      - name: Publish test summary
        if: ${{ github.event_name == 'push' }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          junit_files: "**/build/test-results/test/TEST-*.xml"
